-- Splunky initial database schema
-- Historical baseline only. The current effective LLM credential shape is
-- simplified by V4__simplify_llm_credential_storage.sql.
-- Target: PostgreSQL 16
-- Backend: Java 17 + Spring Boot 3
-- Notes:
--   1. All application tables use the spky_ prefix.
--   2. Flyway history table must be configured as spky_flyway_schema_history via spring.flyway.table.
--   3. Do not create spky_flyway_schema_history manually; Flyway creates it.
--   4. UUID values are expected to be generated by the application.

CREATE TABLE spky_user_account (
    user_id UUID PRIMARY KEY,
    username VARCHAR(128) NOT NULL,
    display_name VARCHAR(256),
    email VARCHAR(256),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_spky_user_account_username UNIQUE (username),
    CONSTRAINT ck_spky_user_account_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE spky_user_session (
    session_id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    splunk_username VARCHAR(128) NOT NULL,
    environment VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    last_activity_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_spky_user_session_user FOREIGN KEY (user_id) REFERENCES spky_user_account(user_id),
    CONSTRAINT ck_spky_user_session_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'LOGGED_OUT'))
);

CREATE TABLE spky_llm_credential (
    credential_id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    provider VARCHAR(64) NOT NULL,
    credential_type VARCHAR(64) NOT NULL,
    encrypted_secret TEXT NOT NULL,
    secret_fingerprint VARCHAR(128),
    expires_at TIMESTAMPTZ,
    last_refreshed_at TIMESTAMPTZ,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_spky_llm_credential_user FOREIGN KEY (user_id) REFERENCES spky_user_account(user_id),
    CONSTRAINT ck_spky_llm_credential_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'REVOKED'))
);

CREATE TABLE spky_investigation (
    investigation_id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    session_id UUID,
    title VARCHAR(512) NOT NULL,
    environment VARCHAR(64) NOT NULL,
    initial_input_type VARCHAR(64) NOT NULL,
    initial_input_text TEXT NOT NULL,
    active_run_id UUID,
    status VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_spky_investigation_user FOREIGN KEY (user_id) REFERENCES spky_user_account(user_id),
    CONSTRAINT fk_spky_investigation_session FOREIGN KEY (session_id) REFERENCES spky_user_session(session_id),
    CONSTRAINT ck_spky_investigation_input_type CHECK (initial_input_type IN ('CORRELATION_ID', 'ERROR_RESPONSE', 'API_NAME', 'FIELD_VALUE', 'NATURAL_LANGUAGE', 'UNKNOWN')),
    CONSTRAINT ck_spky_investigation_status CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED', 'ARCHIVED'))
);

CREATE TABLE spky_investigation_run (
    run_id UUID PRIMARY KEY,
    investigation_id UUID NOT NULL,
    run_no INTEGER NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    user_prompt TEXT NOT NULL,
    intent VARCHAR(128),
    detected_entities_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    time_range_from TIMESTAMPTZ,
    time_range_to TIMESTAMPTZ,
    status VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
    final_status VARCHAR(64),
    failure_point VARCHAR(512),
    hypothesis TEXT,
    confidence VARCHAR(32),
    summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    result_payload_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT fk_spky_investigation_run_investigation FOREIGN KEY (investigation_id) REFERENCES spky_investigation(investigation_id),
    CONSTRAINT uk_spky_investigation_run_no UNIQUE (investigation_id, run_no),
    CONSTRAINT ck_spky_investigation_run_trigger CHECK (trigger_type IN ('INITIAL', 'FOLLOW_UP_RERUN', 'MANUAL_RERUN')),
    CONSTRAINT ck_spky_investigation_run_status CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_spky_investigation_run_final_status CHECK (final_status IS NULL OR final_status IN ('SUCCESS', 'FAILED', 'PARTIAL', 'UNKNOWN')),
    CONSTRAINT ck_spky_investigation_run_confidence CHECK (confidence IS NULL OR confidence IN ('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN'))
);

ALTER TABLE spky_investigation
    ADD CONSTRAINT fk_spky_investigation_active_run
    FOREIGN KEY (active_run_id) REFERENCES spky_investigation_run(run_id);

CREATE TABLE spky_chat_message (
    message_id UUID PRIMARY KEY,
    investigation_id UUID NOT NULL,
    run_id UUID,
    role VARCHAR(32) NOT NULL,
    message_type VARCHAR(64) NOT NULL,
    content TEXT NOT NULL,
    action VARCHAR(64),
    metadata_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_spky_chat_message_investigation FOREIGN KEY (investigation_id) REFERENCES spky_investigation(investigation_id),
    CONSTRAINT fk_spky_chat_message_run FOREIGN KEY (run_id) REFERENCES spky_investigation_run(run_id),
    CONSTRAINT ck_spky_chat_message_role CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM')),
    CONSTRAINT ck_spky_chat_message_action CHECK (action IS NULL OR action IN ('ANSWER_FROM_CURRENT_RESULT', 'REFINE_ANALYSIS', 'RERUN_QUERY', 'NEW_INVESTIGATION'))
);

CREATE TABLE spky_query_template (
    template_id UUID PRIMARY KEY,
    template_key VARCHAR(128) NOT NULL,
    name VARCHAR(256) NOT NULL,
    description TEXT,
    template_spl TEXT NOT NULL,
    allowed_indexes_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    required_params_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    optional_params_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    default_time_window_minutes INTEGER NOT NULL DEFAULT 30,
    max_time_window_minutes INTEGER NOT NULL DEFAULT 240,
    max_result_count INTEGER NOT NULL DEFAULT 500,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_spky_query_template_key UNIQUE (template_key),
    CONSTRAINT ck_spky_query_template_window CHECK (default_time_window_minutes > 0 AND max_time_window_minutes >= default_time_window_minutes),
    CONSTRAINT ck_spky_query_template_result_count CHECK (max_result_count > 0)
);

CREATE TABLE spky_query_execution (
    query_id UUID PRIMARY KEY,
    run_id UUID NOT NULL,
    template_id UUID,
    template_key VARCHAR(128),
    query_label VARCHAR(256) NOT NULL,
    spl_text TEXT NOT NULL,
    spl_hash VARCHAR(128),
    earliest_time TIMESTAMPTZ,
    latest_time TIMESTAMPTZ,
    splunk_search_id VARCHAR(256),
    splunk_deeplink TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
    result_count INTEGER,
    execution_time_ms INTEGER,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT fk_spky_query_execution_run FOREIGN KEY (run_id) REFERENCES spky_investigation_run(run_id),
    CONSTRAINT fk_spky_query_execution_template FOREIGN KEY (template_id) REFERENCES spky_query_template(template_id),
    CONSTRAINT ck_spky_query_execution_status CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED', 'TIMEOUT')),
    CONSTRAINT ck_spky_query_execution_result_count CHECK (result_count IS NULL OR result_count >= 0),
    CONSTRAINT ck_spky_query_execution_time CHECK (execution_time_ms IS NULL OR execution_time_ms >= 0)
);

CREATE TABLE spky_timeline_event (
    event_id UUID PRIMARY KEY,
    run_id UUID NOT NULL,
    event_order INTEGER NOT NULL,
    event_time TIMESTAMPTZ,
    service_name VARCHAR(256),
    event_type VARCHAR(128) NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
    duration_ms INTEGER,
    message TEXT NOT NULL,
    evidence_refs_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    metadata_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_spky_timeline_event_run FOREIGN KEY (run_id) REFERENCES spky_investigation_run(run_id),
    CONSTRAINT uk_spky_timeline_event_order UNIQUE (run_id, event_order),
    CONSTRAINT ck_spky_timeline_event_status CHECK (status IN ('SUCCESS', 'FAILED', 'TIMEOUT', 'UNKNOWN')),
    CONSTRAINT ck_spky_timeline_event_duration CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE TABLE spky_service_node (
    node_id UUID PRIMARY KEY,
    run_id UUID NOT NULL,
    service_name VARCHAR(256) NOT NULL,
    service_type VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
    platform VARCHAR(64),
    status VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
    log_count INTEGER NOT NULL DEFAULT 0,
    error_count INTEGER NOT NULL DEFAULT 0,
    first_seen_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    metadata_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_spky_service_node_run FOREIGN KEY (run_id) REFERENCES spky_investigation_run(run_id),
    CONSTRAINT uk_spky_service_node_name UNIQUE (run_id, service_name),
    CONSTRAINT ck_spky_service_node_type CHECK (service_type IN ('API', 'GATEWAY', 'DOWNSTREAM', 'DATABASE', 'UNKNOWN')),
    CONSTRAINT ck_spky_service_node_status CHECK (status IN ('SUCCESS', 'FAILED', 'PARTIAL', 'UNKNOWN')),
    CONSTRAINT ck_spky_service_node_counts CHECK (log_count >= 0 AND error_count >= 0)
);

CREATE TABLE spky_service_edge (
    edge_id UUID PRIMARY KEY,
    run_id UUID NOT NULL,
    caller_service VARCHAR(256) NOT NULL,
    callee_service VARCHAR(256) NOT NULL,
    operation VARCHAR(512),
    status VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
    latency_ms INTEGER,
    call_count INTEGER NOT NULL DEFAULT 1,
    confidence VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    evidence_refs_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    metadata_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_spky_service_edge_run FOREIGN KEY (run_id) REFERENCES spky_investigation_run(run_id),
    CONSTRAINT ck_spky_service_edge_status CHECK (status IN ('SUCCESS', 'FAILED', 'TIMEOUT', 'UNKNOWN')),
    CONSTRAINT ck_spky_service_edge_confidence CHECK (confidence IN ('CONFIRMED', 'INFERRED', 'UNKNOWN')),
    CONSTRAINT ck_spky_service_edge_latency CHECK (latency_ms IS NULL OR latency_ms >= 0),
    CONSTRAINT ck_spky_service_edge_call_count CHECK (call_count >= 0)
);

CREATE TABLE spky_downstream_call (
    call_id UUID PRIMARY KEY,
    run_id UUID NOT NULL,
    call_order INTEGER NOT NULL,
    caller_service VARCHAR(256),
    downstream_service VARCHAR(256) NOT NULL,
    http_method VARCHAR(16),
    endpoint VARCHAR(1024),
    operation VARCHAR(512),
    status VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',
    status_code INTEGER,
    latency_ms INTEGER,
    error_code VARCHAR(256),
    error_message TEXT,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    evidence_refs_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    metadata_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_spky_downstream_call_run FOREIGN KEY (run_id) REFERENCES spky_investigation_run(run_id),
    CONSTRAINT uk_spky_downstream_call_order UNIQUE (run_id, call_order),
    CONSTRAINT ck_spky_downstream_call_status CHECK (status IN ('SUCCESS', 'FAILED', 'TIMEOUT', 'UNKNOWN')),
    CONSTRAINT ck_spky_downstream_call_status_code CHECK (status_code IS NULL OR (status_code >= 100 AND status_code <= 599)),
    CONSTRAINT ck_spky_downstream_call_latency CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE TABLE spky_feedback (
    feedback_id UUID PRIMARY KEY,
    investigation_id UUID NOT NULL,
    run_id UUID,
    message_id UUID,
    user_id UUID NOT NULL,
    rating VARCHAR(32) NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_spky_feedback_investigation FOREIGN KEY (investigation_id) REFERENCES spky_investigation(investigation_id),
    CONSTRAINT fk_spky_feedback_run FOREIGN KEY (run_id) REFERENCES spky_investigation_run(run_id),
    CONSTRAINT fk_spky_feedback_message FOREIGN KEY (message_id) REFERENCES spky_chat_message(message_id),
    CONSTRAINT fk_spky_feedback_user FOREIGN KEY (user_id) REFERENCES spky_user_account(user_id),
    CONSTRAINT ck_spky_feedback_rating CHECK (rating IN ('HELPFUL', 'NOT_HELPFUL'))
);

CREATE TABLE spky_audit_event (
    audit_id UUID PRIMARY KEY,
    user_id UUID,
    session_id UUID,
    event_type VARCHAR(128) NOT NULL,
    target_type VARCHAR(128),
    target_id UUID,
    summary TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_spky_audit_event_user FOREIGN KEY (user_id) REFERENCES spky_user_account(user_id),
    CONSTRAINT fk_spky_audit_event_session FOREIGN KEY (session_id) REFERENCES spky_user_session(session_id)
);

CREATE INDEX idx_spky_user_session_user_status ON spky_user_session(user_id, status);
CREATE INDEX idx_spky_user_session_expires_at ON spky_user_session(expires_at);

CREATE INDEX idx_spky_llm_credential_user_provider ON spky_llm_credential(user_id, provider);
CREATE INDEX idx_spky_llm_credential_status ON spky_llm_credential(status);

CREATE INDEX idx_spky_investigation_user_created ON spky_investigation(user_id, created_at DESC);
CREATE INDEX idx_spky_investigation_status ON spky_investigation(status);
CREATE INDEX idx_spky_investigation_environment ON spky_investigation(environment);

CREATE INDEX idx_spky_investigation_run_investigation ON spky_investigation_run(investigation_id, run_no DESC);
CREATE INDEX idx_spky_investigation_run_status ON spky_investigation_run(status);
CREATE INDEX idx_spky_investigation_run_created ON spky_investigation_run(created_at DESC);

CREATE INDEX idx_spky_chat_message_investigation_created ON spky_chat_message(investigation_id, created_at ASC);
CREATE INDEX idx_spky_chat_message_run ON spky_chat_message(run_id);

CREATE INDEX idx_spky_query_template_enabled ON spky_query_template(enabled);
CREATE INDEX idx_spky_query_execution_run_created ON spky_query_execution(run_id, created_at ASC);
CREATE INDEX idx_spky_query_execution_template_key ON spky_query_execution(template_key);
CREATE INDEX idx_spky_query_execution_status ON spky_query_execution(status);

CREATE INDEX idx_spky_timeline_event_run_order ON spky_timeline_event(run_id, event_order ASC);
CREATE INDEX idx_spky_timeline_event_run_time ON spky_timeline_event(run_id, event_time ASC);

CREATE INDEX idx_spky_service_node_run_name ON spky_service_node(run_id, service_name);
CREATE INDEX idx_spky_service_edge_run_caller_callee ON spky_service_edge(run_id, caller_service, callee_service);

CREATE INDEX idx_spky_downstream_call_run_order ON spky_downstream_call(run_id, call_order ASC);
CREATE INDEX idx_spky_downstream_call_downstream_status ON spky_downstream_call(downstream_service, status);

CREATE INDEX idx_spky_feedback_investigation_created ON spky_feedback(investigation_id, created_at DESC);
CREATE INDEX idx_spky_feedback_run ON spky_feedback(run_id);

CREATE INDEX idx_spky_audit_event_user_created ON spky_audit_event(user_id, created_at DESC);
CREATE INDEX idx_spky_audit_event_session_created ON spky_audit_event(session_id, created_at DESC);
CREATE INDEX idx_spky_audit_event_type_created ON spky_audit_event(event_type, created_at DESC);
