INSERT INTO spky_query_template (
    template_id,
    template_key,
    name,
    description,
    template_spl,
    allowed_indexes_json,
    required_params_json,
    optional_params_json,
    default_time_window_minutes,
    max_time_window_minutes,
    max_result_count,
    enabled,
    created_at,
    updated_at
) VALUES
(
    '00000000-0000-4000-8000-000000000001',
    'FIND_EVENTS_BY_CORRELATION_ID',
    'Find events by correlation ID',
    'Fetch all request-level events for one correlation ID.',
    'index=${index} ${correlationField}="${correlationId}" earliest=${earliest} latest=${latest} | sort _time',
    '["test-*"]'::jsonb,
    '["index", "correlationField", "correlationId", "earliest", "latest"]'::jsonb,
    '[]'::jsonb,
    30,
    240,
    500,
    true,
    now(),
    now()
),
(
    '00000000-0000-4000-8000-000000000002',
    'FIND_ERRORS_BY_CORRELATION_ID',
    'Find errors by correlation ID',
    'Fetch error and warning events for one correlation ID.',
    'index=${index} ${correlationField}="${correlationId}" earliest=${earliest} latest=${latest} (level=ERROR OR level=WARN OR "Exception" OR "timeout") | sort _time',
    '["test-*"]'::jsonb,
    '["index", "correlationField", "correlationId", "earliest", "latest"]'::jsonb,
    '[]'::jsonb,
    30,
    240,
    200,
    true,
    now(),
    now()
),
(
    '00000000-0000-4000-8000-000000000003',
    'FIND_API_ERRORS_BY_TIME_RANGE',
    'Find API errors by time range',
    'Fetch recent errors for an API over a controlled time window.',
    'index=${index} service="${apiName}" earliest=${earliest} latest=${latest} (level=ERROR OR status>=500 OR "Exception") | sort -_time | head ${limit}',
    '["test-*"]'::jsonb,
    '["index", "apiName", "earliest", "latest"]'::jsonb,
    '["limit"]'::jsonb,
    30,
    240,
    500,
    true,
    now(),
    now()
),
(
    '00000000-0000-4000-8000-000000000004',
    'FIND_DOWNSTREAM_TIMEOUTS',
    'Find downstream timeouts',
    'Fetch timeout events for one downstream dependency.',
    'index=${index} downstream="${downstream}" earliest=${earliest} latest=${latest} ("timeout" OR "Read timed out" OR status=504) | sort -_time | head ${limit}',
    '["test-*"]'::jsonb,
    '["index", "downstream", "earliest", "latest"]'::jsonb,
    '["limit"]'::jsonb,
    60,
    240,
    500,
    true,
    now(),
    now()
)
ON CONFLICT (template_key) DO UPDATE SET
    name = excluded.name,
    description = excluded.description,
    template_spl = excluded.template_spl,
    allowed_indexes_json = excluded.allowed_indexes_json,
    required_params_json = excluded.required_params_json,
    optional_params_json = excluded.optional_params_json,
    default_time_window_minutes = excluded.default_time_window_minutes,
    max_time_window_minutes = excluded.max_time_window_minutes,
    max_result_count = excluded.max_result_count,
    enabled = excluded.enabled,
    updated_at = now();
